bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'hc-run-agent'
keystore_file = 'player1.key'
name = 'agent1'
public_address = 'HcScjsR4AVE6T4bxaoruYeh6ybPeyjgdvuvnW7Y4PQYfgntgUmwZSqpH5gwrutr'
test_agent = false

[[dnas]]
file = './dist/dna.dna.json'
hash = 'QmReFkgf8sjrdq8PUpa68hX1Gpv8Fo321S1x4oGYPAPZar'
id = 'hc-run-dna'

[[instances]]
agent = 'hc-run-agent'
dna = 'hc-run-dna'
id = 'test-instance'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'test-instance'

[interfaces.driver]
port = 9999
type = 'websocket'

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
