bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'mutual-agent'
keystore_file = 'player2.key'
name = 'agent2'
public_address = 'HcScJ3nziT6NPxn8i7EOAgd9nhpkhugmozISNBnuks6ti8ppdx6gK4du39Xjjra'
test_agent = false

[[dnas]]
file = './dist/dna.dna.json'
hash = 'QmaYiSmKoyiT9za4HPGoviqp3N4VCBrYX3TfwTs6g2v3zt'
id = 'mutualize'

[[instances]]
agent = 'mutual-agent'
dna = 'mutualize'
id = 'Qmf6LZZTNwakq739EfCMJjzrr7cGzD9pWTgm8sNMebMGjA'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'Qmf6LZZTNwakq739EfCMJjzrr7cGzD9pWTgm8sNMebMGjA'

[interfaces.driver]
port = 8888
type = 'websocket'

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
